# Generated by Django 4.1.5 on 2023-02-01 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team_players',
            field=models.ManyToManyField(related_name='away_team_players', to='players.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_players',
            field=models.ManyToManyField(related_name='home_team_players', to='players.player'),
        ),
    ]
