# Generated by Django 4.1.7 on 2023-03-16 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_alter_position_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name_plural': 'positions'},
        ),
    ]
